services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'nutri_mysql'
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nutrifit
      MYSQL_USER: nutrifituser
      MYSQL_PASSWORD: nutripass
    volumes:
      - 'mysql_data:/var/lib/mysql'

volumes:
  mysql_data: